# Use https://marketplace.visualstudio.com/items?itemName=humao.rest-client to execute these in VSCode

### Delete Peer
DELETE https://chrysalis-nodes.iota.org/api/v1/peers/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA
