export const MAX_INDEX_DIFF = 1000

export const HASH_SIZE = 81
export const TAG_SIZE = 27
export const SIGNATURE_MESSAGE_FRAGMENT_SIZE = 2187
export const TRANSACTION_TRYTES_SIZE = 2673

export const NULL_HASH_TRYTES = '9'.repeat(HASH_SIZE)
export const NULL_TAG_TRYTES = '9'.repeat(TAG_SIZE)
export const NULL_SIGNATURE_MESSAGE_FRAGMENT_TRYTES = '9'.repeat(SIGNATURE_MESSAGE_FRAGMENT_SIZE)